'use client';

import { useState, useEffect, useRef } from 'react';
import {
  SiGithub, SiSentry, SiSlack, SiStripe, SiIntercom
} from 'react-icons/si';
import { TbFlag, TbRadar, TbDatabase, TbDatabaseOff } from 'react-icons/tb';
import { RiUploadCloud2Line } from 'react-icons/ri';
import { ChatInterface } from '@/components/ChatInterface';
import { IncidentTimeline } from '@/components/IncidentTimeline';
import { ImpactCard } from '@/components/ImpactCard';
import { QueryViewer } from '@/components/QueryViewer';
import { CausalChainGraph } from '@/components/CausalChainGraph';
import { RemediationPanel } from '@/components/RemediationPanel';
import { FlagSafetyScore } from '@/components/FlagSafetyScore';
import { OrgPulseFeed } from '@/components/OrgPulseFeed';
import { DeepDiagnosisPanel } from '@/components/DeepDiagnosisPanel';
import { SilentChurnPanel } from '@/components/SilentChurnPanel';
import { AnalysisResponse, AnomalySignal, Incident, TimelineEvent, getIncidents, streamAnalyze, simulateAnomaly } from '@/lib/api';

function extractFlagKey(timeline: TimelineEvent[]): string {
  for (const e of timeline) {
    if (e.source === 'launchdarkly') {
      const meta = e.metadata as Record<string, unknown> | undefined;
      if (meta?.flag_key) return String(meta.flag_key);
    }
  }
  return 'new-upload-flow';
}

const SOURCE_ICON: Record<string, React.ReactNode> = {
  launchdarkly: <TbFlag className="w-3 h-3" />,
  github: <SiGithub className="w-3 h-3" />,
  sentry: <SiSentry className="w-3 h-3" />,
  slack: <SiSlack className="w-3 h-3" />,
  stripe: <SiStripe className="w-3 h-3" />,
  intercom: <SiIntercom className="w-3 h-3" />,
};

const SEVERITY_BADGE: Record<string, string> = {
  P0: 'bg-red-500/20 text-red-400 border border-red-500/30',
  P1: 'bg-orange-500/20 text-orange-400 border border-orange-500/30',
  P2: 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30'
};

const STATUS_DOT: Record<string, string> = {
  active: 'bg-red-400 animate-pulse',
  investigating: 'bg-yellow-400 animate-pulse',
  resolved: 'bg-emerald-400'
};

const STATUS_LABEL: Record<string, string> = {
  active: 'text-red-400',
  investigating: 'text-yellow-400',
  resolved: 'text-emerald-400'
};

const INCIDENT_QUESTION: Record<string, string> = {
  'inc-001': 'Why are uploads failing?',
  'inc-002': 'Why is auth latency spiking?',
  'inc-003': 'Why are dashboards timing out?',
};

function TypewriterText({ text }: { text: string }) {
  const [displayed, setDisplayed] = useState('');

  useEffect(() => {
    setDisplayed('');
    let i = 0;
    const timer = setInterval(() => {
      i++;
      setDisplayed(text.slice(0, i));
      if (i >= text.length) clearInterval(timer);
    }, 16);
    return () => clearInterval(timer);
  }, [text]);

  return (
    <span>
      {displayed}
      {displayed.length < text.length && (
        <span className="animate-pulse text-orange-300 ml-0.5">|</span>
      )}
    </span>
  );
}

function exportReport(analysis: AnalysisResponse) {
  const lines = [
    `PulseIQ Incident Report — ${new Date().toISOString()}`,
    `${'='.repeat(60)}`,
    `Incident ID : ${analysis.incidentId}`,
    `Question    : ${analysis.question}`,
    `Confidence  : ${analysis.confidence}`,
    ``,
    `SUMMARY`,
    analysis.summary,
    ``,
    `ROOT CAUSE`,
    analysis.root_cause,
    ``,
    `RECOMMENDED ACTION`,
    analysis.recommended_action,
    ``,
    `BUSINESS IMPACT`,
    `  MRR at Risk        : $${analysis.mrr_at_risk.toLocaleString()}`,
    `  Affected Customers : ${analysis.affected_customers.length}`,
    `  Support Tickets    : ${analysis.support_ticket_count}`,
    ``,
    `SOURCES QUERIED`,
    `  ${analysis.sources_queried.join(', ')}`,
    ``,
    `CORAL SQL`,
    analysis.coral_query,
    ``,
    `Generated by PulseIQ — Powered by Coral`,
  ];
  navigator.clipboard.writeText(lines.join('\n'));
}

export default function Home() {
  const [analysis, setAnalysis] = useState<AnalysisResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [sourceDone, setSourceDone] = useState<Record<string, { rows: number; live: boolean }>>({});
  const [copied, setCopied] = useState(false);
  const [activeIncidentId, setActiveIncidentId] = useState<string | null>(null);
  const [autopilot, setAutopilot] = useState(false);
  const autopilotESRef = useRef<EventSource | null>(null);
  const [autopilotLabel, setAutopilotLabel] = useState<string | null>(null);
  const [seedEnabled, setSeedEnabled] = useState(true);
  const [coralConnected, setCoralConnected] = useState<boolean | null>(null);

  useEffect(() => {
    getIncidents().then(setIncidents).catch(() => {});
  }, []);

  useEffect(() => {
    const checkCoral = () => {
      fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'}/api/health/coral`)
        .then(r => r.json())
        .then((d: { connected: boolean }) => setCoralConnected(d.connected))
        .catch(() => setCoralConnected(false));
    };
    checkCoral();
    const interval = setInterval(checkCoral, 15000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    return () => {
      autopilotESRef.current?.close();
    };
  }, []);

  function handleIncidentClick(inc: Incident) {
    if (loading) return;
    setActiveIncidentId(inc.id);
    setLoading(true);
    setAnalysis(null);
    setSourceDone({});

    const question = INCIDENT_QUESTION[inc.id] || `What caused ${inc.title}?`;
    const doneRef: Record<string, { rows: number; live: boolean }> = {};

    streamAnalyze(
      question,
      (event) => {
        if (event.type === 'source_done') {
          const src = event.data.source as string;
          doneRef[src] = { rows: event.data.rows as number, live: event.data.live as boolean };
          setSourceDone({ ...doneRef });
        }
      },
      (result) => {
        setAnalysis(result);
        setLoading(false);
      },
      () => {
        setLoading(false);
      },
      seedEnabled
    );
  }

  function handleExport() {
    if (!analysis) return;
    exportReport(analysis);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function toggleAutopilot() {
    if (autopilot) {
      autopilotESRef.current?.close();
      autopilotESRef.current = null;
      setAutopilot(false);
      setAutopilotLabel(null);
      return;
    }

    setAutopilot(true);
    setAutopilotLabel(null);
    setAnalysis(null);
    setSourceDone({});

    const BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
    const es = new EventSource(`${BASE}/api/autopilot/stream`);
    autopilotESRef.current = es;

    const doneRef: Record<string, { rows: number; live: boolean }> = {};

    es.addEventListener('anomaly_detected', (e: MessageEvent) => {
      const data = JSON.parse(e.data) as AnomalySignal;
      setAutopilotLabel(`Autopilot detected: ${data.signal}`);
      setLoading(true);
      setAnalysis(null);
      setSourceDone({});
      Object.keys(doneRef).forEach(k => delete doneRef[k]);
    });

    es.addEventListener('source_done', (e: MessageEvent) => {
      const data = JSON.parse(e.data);
      const src = data.source as string;
      doneRef[src] = { rows: data.rows as number, live: data.live as boolean };
      setSourceDone({ ...doneRef });
    });

    es.addEventListener('complete', (e: MessageEvent) => {
      const data = JSON.parse(e.data);
      setAnalysis(data);
      setLoading(false);
    });

    es.addEventListener('remediation_complete', (e: MessageEvent) => {
      const data = JSON.parse(e.data) as { duration_ms: number; pr_url?: string; flag_disabled?: boolean };
      const secs = (data.duration_ms / 1000).toFixed(1);
      const pr = data.pr_url ? ` · PR opened` : '';
      const flag = data.flag_disabled ? ' · flag disabled' : '';
      setAutopilotLabel(`Auto-remediated in ${secs}s${flag}${pr} — zero human touch`);
    });

    es.addEventListener('error', (e: Event) => {
      const msgEvent = e as MessageEvent;
      if (msgEvent.data) {
        try {
          const data = JSON.parse(msgEvent.data);
          if (data?.fallback) setAnalysis(data.fallback);
        } catch { /* ignore */ }
      }
      setLoading(false);
    });

    es.onerror = () => setLoading(false);
  }

  async function handleSimulate() {
    try {
      const signal = await simulateAnomaly();
      setAutopilotLabel(`Autopilot detected: ${signal.signal}`);
      setLoading(true);
      setAnalysis(null);
      setSourceDone({});
      const doneRef: Record<string, { rows: number; live: boolean }> = {};

      streamAnalyze(
        signal.question,
        (event) => {
          if (event.type === 'source_done') {
            const src = event.data.source as string;
            doneRef[src] = { rows: event.data.rows as number, live: event.data.live as boolean };
            setSourceDone({ ...doneRef });
          }
        },
        (result) => {
          setAnalysis(result);
          setLoading(false);
        },
        () => setLoading(false),
        seedEnabled
      );
    } catch {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-slate-50 flex" style={{ fontFamily: 'var(--font-inter), Inter, sans-serif' }}>

      {/* Sidebar */}
      <aside className="w-64 bg-slate-950 flex flex-col shrink-0 overflow-y-auto">

        {/* Logo */}
        <div className="px-5 py-5 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-linear-to-br from-blue-500 to-blue-700 flex items-center justify-center shadow-lg shadow-blue-500/25">
              <RiUploadCloud2Line className="w-4 h-4 text-white" />
            </div>
            <div>
              <h1 className="text-sm font-bold text-white tracking-tight">PulseIQ</h1>
              <p className="text-xs text-slate-500">Powered by Coral</p>
            </div>
          </div>
        </div>

        {/* Incidents */}
        <div className="px-4 py-4 flex-1">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-widest mb-3 px-1">
            Recent Incidents
          </p>
          <div className="space-y-2">
            {incidents.map(inc => (
              <button
                key={inc.id}
                onClick={() => handleIncidentClick(inc)}
                disabled={loading}
                className={`w-full text-left p-3 rounded-xl border transition-all group ${
                  activeIncidentId === inc.id
                    ? 'bg-slate-700 border-slate-500'
                    : 'bg-slate-900 border-slate-800 hover:border-slate-600 hover:bg-slate-800'
                } ${loading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
              >
                <div className="flex items-center gap-2 mb-1.5">
                  <span className={`text-xs px-1.5 py-0.5 rounded-md font-bold ${SEVERITY_BADGE[inc.severity] || 'bg-slate-700 text-slate-300'}`}>
                    {inc.severity}
                  </span>
                  <div className="flex items-center gap-1">
                    <div className={`w-1.5 h-1.5 rounded-full ${STATUS_DOT[inc.status] || 'bg-slate-500'}`} />
                    <span className={`text-xs ${STATUS_LABEL[inc.status] || 'text-slate-400'}`}>{inc.status}</span>
                  </div>
                </div>
                <p className="text-xs font-medium text-slate-200 leading-tight group-hover:text-white transition-colors">
                  {inc.title}
                </p>
                <p className="text-xs text-red-400 font-mono mt-1.5">
                  ${inc.mrr_at_risk.toLocaleString()} MRR
                </p>
              </button>
            ))}
          </div>
        </div>

        {/* Coral Sources */}
        <div className="px-4 py-4 border-t border-slate-800">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-widest mb-3 px-1">
            Coral Sources
          </p>
          <div className="space-y-1.5">
            {(['launchdarkly', 'github', 'sentry', 'slack', 'stripe', 'intercom'] as const).map(s => {
              const result = sourceDone[s];
              const queried = s in sourceDone;
              const isLive = result?.live;
              return (
                <div key={s} className="flex items-center gap-2 px-1">
                  <div className={`w-1.5 h-1.5 rounded-full transition-colors ${
                    queried ? (isLive ? 'bg-emerald-400' : 'bg-yellow-400') : 'bg-slate-600'
                  }`} />
                  <span className="text-slate-500 flex items-center gap-1.5 flex-1">
                    <span className="text-slate-400">{SOURCE_ICON[s]}</span>
                    <span className="text-xs text-slate-400">{s}</span>
                  </span>
                  {queried && (
                    <span className={`text-xs font-mono ${isLive ? 'text-emerald-500' : 'text-yellow-500'}`}>
                      {isLive ? `${result.rows}r` : 'seed'}
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </aside>

      {/* Main */}
      <main className="flex-1 overflow-y-auto">

        {/* Top bar */}
        <div className="sticky top-0 z-10 bg-white/80 backdrop-blur border-b border-slate-200 px-8 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 rounded-full bg-emerald-400" />
            <span className="text-xs text-slate-500 font-medium">Live · all sources connected</span>
            {autopilot && (
              <button
                onClick={handleSimulate}
                disabled={loading}
                className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 border border-slate-200 text-xs text-slate-600 font-medium transition-colors disabled:opacity-40"
              >
                Simulate
              </button>
            )}
          </div>
          <div className="flex items-center gap-3">
            {/* Coral connection status */}
            <div
              className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-semibold border ${
                coralConnected === true
                  ? 'bg-emerald-50 border-emerald-300 text-emerald-700'
                  : coralConnected === false
                  ? 'bg-red-50 border-red-200 text-red-500'
                  : 'bg-slate-50 border-slate-200 text-slate-400'
              }`}
              title={coralConnected === true ? 'Coral CLI connected' : coralConnected === false ? 'Coral CLI not found — seed data only' : 'Checking Coral...'}
            >
              <span className={`w-1.5 h-1.5 rounded-full ${
                coralConnected === true ? 'bg-emerald-500' : coralConnected === false ? 'bg-red-400' : 'bg-slate-300'
              }`} />
              {coralConnected === true ? 'Coral' : coralConnected === false ? 'Coral Offline' : 'Coral...'}
            </div>
            <button
              onClick={() => setSeedEnabled(s => !s)}
              className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-semibold transition-all border ${
                seedEnabled
                  ? 'bg-amber-50 border-amber-300 text-amber-700 hover:bg-amber-100'
                  : 'bg-slate-100 border-slate-200 text-slate-500 hover:border-slate-300'
              }`}
              title={seedEnabled ? 'Seed data on — click for live only' : 'Live only — click to enable seed fallback'}
            >
              {seedEnabled ? <TbDatabase className="w-3.5 h-3.5" /> : <TbDatabaseOff className="w-3.5 h-3.5" />}
              {seedEnabled ? 'Seed' : 'Live'}
            </button>
            <button
              onClick={toggleAutopilot}
              disabled={loading}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold transition-all border ${
                autopilot
                  ? 'bg-emerald-50 border-emerald-300 text-emerald-700'
                  : 'bg-slate-100 border-slate-200 text-slate-500 hover:border-slate-300'
              }`}
            >
              <TbRadar className={`w-3.5 h-3.5 ${autopilot ? 'animate-pulse' : ''}`} />
              {autopilot ? 'Monitoring org...' : 'Autopilot'}
            </button>
            <span className="text-xs text-slate-400">PulseIQ — Organizational Intelligence</span>
          </div>
        </div>

        <div className="p-8 max-w-4xl mx-auto space-y-6">

          {/* Alert banner */}
          {analysis && !loading && (
            <div className="relative overflow-hidden rounded-2xl bg-linear-to-r from-red-600 to-orange-500 p-px shadow-lg shadow-red-500/20">
              <div className="rounded-2xl bg-linear-to-r from-red-950/90 to-orange-950/90 px-5 py-4 backdrop-blur">
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <p className="text-xs font-semibold text-orange-400 uppercase tracking-wider mb-1">
                      {autopilotLabel ?? 'AI Analysis Complete'}
                    </p>
                    <p className="text-white/90 text-sm leading-relaxed font-medium">
                      <TypewriterText text={analysis.summary} />
                    </p>
                  </div>
                  <button
                    onClick={handleExport}
                    className="shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 text-xs text-white font-medium transition-colors"
                  >
                    {copied ? 'Copied' : 'Export'}
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Loading state for incident click */}
          {loading && (
            <div className="flex items-center gap-3 p-4 rounded-2xl bg-slate-100 border border-slate-200">
              <span className="w-4 h-4 border-2 border-slate-400 border-t-blue-500 rounded-full animate-spin shrink-0" />
              <span className="text-sm text-slate-500 font-medium">Querying sources via Coral...</span>
            </div>
          )}

          {/* Org Pulse Feed — always on */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <OrgPulseFeed seedEnabled={seedEnabled} />
          </div>

          {/* Chat */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <div className="flex items-center gap-2 mb-5">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
              <h2 className="text-sm font-semibold text-slate-700">Ask PulseIQ</h2>
            </div>
            <ChatInterface
              onAnalysis={setAnalysis}
              isLoading={loading}
              setLoading={setLoading}
              onSourcesUpdate={setSourceDone}
            />
          </div>

          {/* Timeline */}
          {analysis && !loading && (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
              <IncidentTimeline events={analysis.timeline} />
            </div>
          )}

          {/* Causal Chain */}
          {analysis && !loading && analysis.timeline.length > 1 && (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
              <CausalChainGraph events={analysis.timeline} />
            </div>
          )}

          {/* Flag Safety Score */}
          {analysis && !loading && (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
              <FlagSafetyScore flagKey={extractFlagKey(analysis.timeline)} seed={seedEnabled} />
            </div>
          )}

          {/* Deep Diagnosis */}
          {analysis && !loading && (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
              <DeepDiagnosisPanel
                flagKey={extractFlagKey(analysis.timeline)}
                incidentId={analysis.incidentId}
                seed={seedEnabled}
              />
            </div>
          )}

          {/* Silent Churn Detector */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <SilentChurnPanel seedEnabled={seedEnabled} />
          </div>

          {/* Remediation */}
          {analysis && !loading && (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
              <RemediationPanel analysis={analysis} />
            </div>
          )}

          {/* Impact + Query */}
          {analysis && !loading && (
            <div className="grid grid-cols-2 gap-6">
              <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
                <ImpactCard
                  mrr_at_risk={analysis.mrr_at_risk}
                  affected_customers={analysis.affected_customers}
                  support_ticket_count={analysis.support_ticket_count}
                  confidence={analysis.confidence}
                />
              </div>
              <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 space-y-4">
                <div className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                  <h2 className="text-sm font-semibold text-slate-700">Coral SQL</h2>
                </div>
                <QueryViewer
                  sql={analysis.coral_query}
                  sources={analysis.sources_queried}
                />
                <div className="text-xs text-slate-400 space-y-2 pt-3 border-t border-slate-100">
                  <div className="flex justify-between items-center">
                    <span>Sources joined</span>
                    <span className="font-semibold text-slate-600 tabular-nums">{analysis.sources_queried.length}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Query type</span>
                    <span className="font-semibold text-slate-600">Cross-source JOIN</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Engine</span>
                    <span className="font-semibold text-blue-600">Coral</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Empty state */}
          {!analysis && !loading && (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-12 h-px bg-slate-200 mb-8" />
              <h3 className="text-slate-600 font-semibold mb-2">Query your organization</h3>
              <p className="text-slate-400 text-sm max-w-sm leading-relaxed">
                PulseIQ joins GitHub, LaunchDarkly, Sentry, Slack, and Stripe in real-time using Coral SQL to surface root cause and business impact.
              </p>
              <div className="w-12 h-px bg-slate-200 mt-8" />
            </div>
          )}

        </div>
      </main>
    </div>
  );
}
