import { Router, Request, Response } from 'express';
import { CoralClient } from '../coral/client';
import { GoogleGenerativeAI } from '@google/generative-ai';

export const postmortemRouter = Router();
const coral = new CoralClient();

const SEED_POSTMORTEM = `# Incident Postmortem — inc-001: Enterprise Upload Failures

**Date:** 2024-05-28 | **Severity:** P0 | **Duration:** 24 minutes (14:31–14:55 UTC)
**Generated by:** PulseIQ Auto-Postmortem via Coral RAG Pipeline

---

## Summary

Enabling the \`new-upload-flow\` flag for 100% of Enterprise customers at 14:31 UTC caused immediate TypeError crashes in \`upload/handler.ts\` for files >10MB, resulting in 847 errors over 24 minutes and $14,200 MRR at risk across 3 Enterprise accounts.

## Timeline

| Time (UTC) | Event | Source |
|---|---|---|
| 14:28 | sarah.chen merges commit \`a3f9c21\` — "feat: new upload flow with chunked transfer" | GitHub |
| 14:31 | \`new-upload-flow\` enabled for 100% Enterprise segment | LaunchDarkly |
| 14:32 | First TypeError: \`Cannot read properties of undefined (reading 'stream')\` in \`upload/handler.ts:47\` | Sentry |
| 14:35 | Error rate reaches 120/min. Acme Corp ($8,400 MRR) first affected | Sentry + Stripe |
| 14:38 | @oncall paged. Slack: "new-upload-flow flag was just enabled for 100% Enterprise — timing matches the spike" | Slack |
| 14:47 | \`new-upload-flow\` disabled. Error rate begins declining | LaunchDarkly |
| 14:55 | Error rate returns to baseline. All 3 affected customers confirmed recovered | Sentry |

## Root Cause

\`file.stream()\` returns \`undefined\` for files >10MB in Safari and older Chromium builds. Commit \`a3f9c21\` replaced \`file.getStream()\` (a widely-supported non-standard alias) with \`file.stream()\` without a null check. When \`new-upload-flow\` was enabled for Enterprise customers — who routinely upload files >10MB — the missing null check caused immediate TypeError crashes.

## Blast Radius

- **847 errors** over 24 minutes
- **3 Enterprise customers** affected: Acme Corp ($8,400/mo), Globex Inc ($6,200/mo), Initech LLC (partial)
- **$14,200 MRR at risk**
- **0 support tickets filed** — all three customers suffered silently (Silent Churn risk)
- **0 data loss** — uploads failed cleanly, no partial writes

## Contributing Factors

1. No integration test for files >10MB before flag enable
2. Flag enabled at 100% immediately — no gradual rollout (1% → 10% → 100%)
3. \`file.stream()\` browser compatibility gap not caught in code review
4. On-call response lag: 6 minutes from first error to page

## Action Items

| Priority | Action | Owner |
|---|---|---|
| P0 | Add null check: \`const stream = file.stream() ?? file.getStream();\` | sarah.chen |
| P0 | Add >10MB upload integration test to CI | Platform team |
| P1 | Enforce gradual rollout policy for upload-path flags | Engineering leads |
| P2 | Migrate Enterprise tier to S3 multipart for files >5MB | Backend team |
| P2 | Set up Silent Churn alerts for Enterprise errors + no tickets | Customer Success |

## What Went Well

- PulseIQ detected root cause within 2 minutes via Coral causal JOIN
- Flag rollback executed in 9 minutes from first error
- No data loss or customer data exposure
`;

interface PostmortemResult {
  incident_id: string;
  markdown: string;
  gemini_used: boolean;
  source: 'live' | 'seed';
}

postmortemRouter.post('/', async (req: Request, res: Response) => {
  const { incident_id = 'inc-001', seed = true } = req.body as {
    incident_id?: string;
    seed?: boolean;
  };

  if (seed) {
    return res.json({ incident_id, markdown: SEED_POSTMORTEM, gemini_used: false, source: 'seed' } satisfies PostmortemResult);
  }

  let timelineRows: Record<string, unknown>[] = [];
  try {
    const [sentryRows, githubRows, ldRows, slackRows] = await Promise.allSettled([
      coral.query(`SELECT title as event, culprit, first_seen as ts FROM sentry.issues WHERE status = 'unresolved' ORDER BY first_seen DESC LIMIT 5`),
      coral.query(`SELECT commit__message as event, commit__author__name as author, commit__author__date as ts FROM github.commits ORDER BY commit__author__date DESC LIMIT 3`),
      coral.query(`SELECT key as event, creation_date as ts FROM launchdarkly.feature_flags LIMIT 3`),
      coral.query(`SELECT text as event, ts FROM slack.messages WHERE channel = 'incidents' ORDER BY ts DESC LIMIT 5`),
    ]);

    if (sentryRows.status === 'fulfilled') timelineRows.push(...sentryRows.value.map(r => ({ ...(r as Record<string, unknown>), source: 'sentry' })));
    if (githubRows.status === 'fulfilled') timelineRows.push(...githubRows.value.map(r => ({ ...(r as Record<string, unknown>), source: 'github' })));
    if (ldRows.status === 'fulfilled') timelineRows.push(...ldRows.value.map(r => ({ ...(r as Record<string, unknown>), source: 'launchdarkly' })));
    if (slackRows.status === 'fulfilled') timelineRows.push(...slackRows.value.map(r => ({ ...(r as Record<string, unknown>), source: 'slack' })));
  } catch { /* use seed */ }

  const geminiKey = process.env.GEMINI_API_KEY;
  if (!timelineRows.length) {
    return res.status(503).json({ error: 'No Coral data available for postmortem generation' });
  }
  if (!geminiKey) {
    return res.status(503).json({ error: 'Gemini API key not configured' });
  }

  try {
    const genAI = new GoogleGenerativeAI(geminiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash', generationConfig: { temperature: 0.1 } });

    const timelineText = timelineRows
      .sort((a, b) => new Date(String(a.ts ?? 0)).getTime() - new Date(String(b.ts ?? 0)).getTime())
      .map(r => `[${String(r.source).toUpperCase()}] ${r.ts}: ${r.event}`)
      .join('\n');

    const result = await model.generateContent(
      `You are a senior SRE. Generate a complete incident postmortem in Markdown for incident ${incident_id}.

Cross-source timeline from Coral JOIN (cite these rows directly):
${timelineText}

Structure: Summary, Timeline table, Root Cause, Blast Radius, Contributing Factors, Action Items, What Went Well.
Every claim must cite specific data from the rows above. Return only the Markdown document.`
    );

    return res.json({ incident_id, markdown: result.response.text(), gemini_used: true, source: 'live' } satisfies PostmortemResult);
  } catch (err) {
    return res.status(500).json({ error: `Gemini generation failed: ${err instanceof Error ? err.message : 'unknown'}` });
  }
});
